// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: athletes.sql

package db

import (
	"context"
)

const getAllAthletes = `-- name: GetAllAthletes :many
SELECT id, name, grade, pr_time, events FROM athletes
`

func (q *Queries) GetAllAthletes(ctx context.Context) ([]Athlete, error) {
	rows, err := q.db.QueryContext(ctx, getAllAthletes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Athlete
	for rows.Next() {
		var i Athlete
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Grade,
			&i.PrTime,
			&i.Events,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAthleteByID = `-- name: GetAthleteByID :one
SELECT id, name, grade, pr_time, events FROM athletes
WHERE id = ?
`

func (q *Queries) GetAthleteByID(ctx context.Context, id int32) (Athlete, error) {
	row := q.db.QueryRowContext(ctx, getAthleteByID, id)
	var i Athlete
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Grade,
		&i.PrTime,
		&i.Events,
	)
	return i, err
}
