// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: meets.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createMeet = `-- name: CreateMeet :execresult
INSERT INTO meets (name, date, location)
VALUES (?, ?, ?)
`

type CreateMeetParams struct {
	Name     string
	Date     time.Time
	Location sql.NullString
}

func (q *Queries) CreateMeet(ctx context.Context, arg CreateMeetParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMeet, arg.Name, arg.Date, arg.Location)
}

const deleteMeet = `-- name: DeleteMeet :exec
DELETE FROM meets WHERE id = ?
`

func (q *Queries) DeleteMeet(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteMeet, id)
	return err
}

const getAllMeets = `-- name: GetAllMeets :many
SELECT id, name, date, location FROM meets
ORDER BY date ASC
`

func (q *Queries) GetAllMeets(ctx context.Context) ([]Meet, error) {
	rows, err := q.db.QueryContext(ctx, getAllMeets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meet
	for rows.Next() {
		var i Meet
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Date,
			&i.Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
